from apps.backend.src.exception import AppBaseException


class BlobServiceException(AppBaseException): ...

class BlobNotFoundError(BlobServiceException): ...

class BlobTooLargeError(BlobServiceException): ...

class UnsupportedContentTypeError(BlobServiceException): ...

class BlobUploadLimitError(BlobServiceException): ...